### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by jeremie-lg** [NVIDIA/gvdb-voxels#30] opened 2018-08-24 13:59 UTC
I try to contruct and destroy a nvdb::VolumeGVDB multiple times. I monitor a memory leak. This simple code illustrates the leak.
`while (1)
 {
   nvdb::VolumeGVDB gvdb;
   gvdb.SetCudaDevice(GVDB_DEV_FIRST);
   gvdb.Initialize();
 }`
Is there a function to free the VolumeGVDB or is this pattern not permitted in gvdb ?

**Comment by ramakarl** [comment] 2019-01-16 20:40
This should work.
Would be interesting to determine the root cause.

**Comment by oursnoir** [comment] 2019-04-24 09:11
Hmm, is there any destructor in the VolumeGVDB class that deallocate the following members ?
- mCudpp (CPU and GPU leak ?)
- mPlan_max (CPU and GPU leak ?)
- mPlan_min (CPU and GPU leak ?)
- mScene (CPU leak ?)
- mPool (CPU and GPU leak ?)
-  cuVDBInfo (GPU leak only)

These are the ones for which I can't find any deallocation code and that I can (without a 100% certainty) relate to the trace given by a cuda-memcheck --leak-check full invocation.

Additionnaly there are no member method of VolumeGVDB that release the memory allocated by mPool. 

I have to do something like (not sure what is absolutely necessary or not though):
```cpp 
gvdb->DestroyChannels();
gvdb->CleanAux();
gvdb->mPool->PoolReleaseAll();
gvdb->Clear();
```
But it doesn't solve the leak from the above-mentioned members.

**Comment by NeilBickford-NV** [comment] 2020-06-19 02:42
Hi all,

I finally implemented destructors for most of the main GVDB classes in cpmmits https://github.com/NVIDIA/gvdb-voxels/commit/dc4d3a0f26bd098850c20ac98d1aca52d8618c4a and https://github.com/NVIDIA/gvdb-voxels/commit/f0d05bb67c902ff74d300e7d4e6eccc1579e59a2.

This makes it so that
`while (1) { nvdb::VolumeGVDB gvdb; gvdb.SetCudaDevice(GVDB_DEV_CURRENT); gvdb.Initialize(); }`
should run without leaking memory (testing in `gRenderKernel`, the amount of memory used appears to be constant). Note that it's important to use `GVDB_DEV_CURRENT` when creating and destroying GVDB objects in a loop like this - otherwise, each GVDB instance will create a new CUDA context just for that instance, and since GVDB allows user code to pick up on the generated CUDA context, will keep the context around (and consequently accumulate CUDA contexts if run in a loop)!
`while (1) { nvdb::VolumeGVDB gvdb; gvdb.SetCudaDevice(GVDB_DEV_FIRST); gvdb.Initialize(); }`

In addition, `cuda-memcheck --leak-check full` should now run cleanly (with the exception of a CUDA/OpenGL interop error) on the three non-interactive samples.

Please let me know if this significantly breaks things, since it also slightly changes the semantics of setting the scene's camera and light objects (these functions now own the pointers that you pass to them), and could cause problems with applications that shared pointers to the same object across multiple volumes.

Hope this helps!

**Comment by NeilBickford-NV** [comment] 2020-08-12 22:20
Closing, since this seems to have been fixed by the commit described in the last post.

**Closed by NeilBickford-NV** 2020-08-12 22:20 UTC
