### ISSUE TITLE
All precompiled samples fail to run on Titan V (Volta) due to CUDPP/PTXAS memory leak(?)

### ISSUE THREAD

**Issue by oscarbg** [NVIDIA/gvdb-voxels#26] opened 2018-07-16 03:36 UTC
Hi,
just changed a GTX 970 by a Titan V.. 
I was expecting all to work ok similar to GTX 970 and even perhaps be able to run fluid surface sample
(https://github.com/NVIDIA/gvdb-voxels/issues/15)..
what I see is no matter if on Windows or Linux using latest drivers (using 398.58 currently but others seem to fail too)..
output is:

```
gInteractiveGL.exe
  Device List:
   0. TITAN V
   Using Device: 0, TITAN V, Context: 000001FDCE9C1D00
Starting GVDB Voxels. ver 1.11
 Creating Allocator..
 Creating Scene..
 Creating CUDPP..
ptxas fatal   : Memory allocation failure
```

before "ptxas fatal   : Memory allocation failure" I see on process manager process gets over 40GB memory before failing as I have 32GB RAM and virtual memory up to 16GB more..
don't know if compiling CUDPP by myself with CUDA 9.2 SDK and explicit sm_70,compute_70 flags would solve the problem..
hope GVDB gets some Volta fixes soon..
thanks..

**Comment by back2yes** [comment] 2019-04-05 08:16
Hi, have you solved this? I met with same error on 1080 Ti.

**Comment by back2yes** [comment] 2019-04-05 10:09
I was using the latest CUDPP from its git repo. That seems to be the problem. Changed to the cudpp codes that came together with GVDB, the problem is solved. Another issue occured in the gFluidSurface example, it throws the following error at runtime:

FLUID SYSTEM, CUDA ERROR:
  Launch status: an illegal memory access was encountered
  Kernel status: no error
  Caller: FluidSystem::TransferFromCUDA
  Call:   cuMemcpyDtoH
  Args:   FPOS
Error. Application will exit.

But I guess this is already another issue.

**Comment by NeilBickford-NV** [comment] 2020-06-08 23:59
Hi oscarbg and back2yes,

Just wanted to let you know that I'm closing this issue because we've since removed CUDPP in version 1.1.1, which seems to have been the source of this issue. Please feel free to reopen this issue or to create a new issue if you're seeing any issues with it - thanks again!

**Closed by NeilBickford-NV** 2020-06-08 23:59 UTC
